// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkazwhfkpwlxmyapwihs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rYXp3aGZrcHdseG15YXB3aWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0OTkyODAsImV4cCI6MjA2OTA3NTI4MH0.TWVNcJMqqvDNoBLg_nTeBiy98s8E4Vae1A8oX7wYtjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});